import type { Metadata } from 'next'
import { Inter, Open_Sans } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import './styles/globals.scss';

const inter = Inter({ subsets: ['latin'] })
const open_sans = Open_Sans({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Mega Menu',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
